services:
  # Контейнер с базой данных
  db:
    image: postgres:16.1-alpine3.19
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    networks:
      - my_network  # Указываем общую сеть

  # Контейнер с Elasticsearch
  elasticsearch:
    image: elasticsearch:8.7.1
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=qwe123QWE
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    restart: always
    networks:
      - my_network  # Указываем общую сеть

volumes:
  postgres_data:
  cache:
  es_data:

networks:
  my_network:  # Определяем сеть
    driver: bridge  # Используем стандартный драйвер
