services:
  # Контейнер с базой данных
  sling-db:
    image: postgres:16.1-alpine3.19
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    expose:
      - 5432
    restart: always
    networks:
      - shared-network

  sling-backend:
    build:
      context: ./backend
    command: >
      sh -c "
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - ./backend:/app
      - ../WWW/sling/media:/app/media
    expose:
      - 8000
    env_file:
      - ./backend/.env
    networks:
      - shared-network
    depends_on:
      - sling-db


  # Контейнер с Elasticsearch
  elasticsearch:
    image: elasticsearch:8.7.1
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=qwe123QWE
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    expose:
      - 9200
    volumes:
      - es_data:/usr/share/elasticsearch/data
    restart: always
    networks:
      - shared-network
    depends_on:
      - sling-backend
    deploy:
      resources:
        limits:
          memory: 1g


networks:
  shared-network:
    external: true

volumes:
  es_data:
