services:
  # Контейнер с базой данных
  db:
    image: postgres:16.1-alpine3.19
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    networks:
      - my_network  # Указываем общую сеть

  # Контейнер с Elasticsearch
  opensearch:
    image: opensearchproject/opensearch:2.12.0  # Стабильная версия, не latest
    container_name: opensearch
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - discovery.type=single-node  # Отключаем кластеризацию (экономит ресурсы)
      - bootstrap.memory_lock=false  # Убираем жесткое резервирование памяти
      - "OPENSEARCH_JAVA_OPTS=-Xms256m -Xmx256m"  # Ограничиваем память JVM
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=sling123SLING  # Пароль админа
#      - OPENSEARCH_SECURITY_DISABLED=true  # Отключаем сложную авторизацию (если не нужна)
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - "9200:9200"
    networks:
      - my_network
    restart: unless-stopped  # Запускаем только если что-то сломалось

volumes:
  postgres_data:
  cache:
  opensearch-data:

networks:
  my_network: # Определяем сеть
    driver: bridge  # Используем стандартный драйвер
