# Generated by Django 5.1.2 on 2025-03-20 09:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dict', '0002_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ИД')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан в')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменен в')),
                ('title', models.CharField(max_length=255, verbose_name='Название изображения')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Ссылка на изображение')),
                ('description', models.TextField(blank=True, default=None, null=True, verbose_name='Описание изображения')),
                ('form_factors', models.ManyToManyField(blank=True, related_name='images', to='dict.formfactor', verbose_name='Форм-факторы')),
                ('tags', models.ManyToManyField(blank=True, related_name='images', to='dict.tag', verbose_name='Тэги')),
                ('work_types', models.ManyToManyField(blank=True, related_name='images', to='dict.worktype', verbose_name='Виды работ')),
            ],
            options={
                'verbose_name': 'Схема строповки',
                'verbose_name_plural': 'Схемы строповки',
                'ordering': ['title'],
            },
        ),
    ]
