# Generated by Django 5.1.2 on 2025-03-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0003_slings'),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='approved_slings',
            field=models.ManyToManyField(related_name='images', to='dict.slings', verbose_name='Применяемые стропы'),
        ),
    ]
