# Generated by Django 5.1.2 on 2025-03-20 06:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormFactor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ИД')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан в')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменен в')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Форм-фактор груза',
                'verbose_name_plural': 'Форм-факторы груза',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ИД')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан в')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменен в')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Вид работы',
                'verbose_name_plural': 'Виды работ',
                'ordering': ['name'],
            },
        ),
    ]
