# Generated by Django 5.1.2 on 2025-01-17 10:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEvents',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ИД')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан в')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменен в')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Справочник статусов',
                'verbose_name_plural': 'Справочник статусов',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='LicenseCategories',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ИД')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан в')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменен в')),
                ('name', models.CharField(max_length=10, verbose_name='Название')),
                ('description', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Справочник категорий ВУ',
                'verbose_name_plural': 'Справочник категорий ВУ',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ИД')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан в')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменен в')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Справочник локаций',
                'verbose_name_plural': 'Справочник локаций',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ИД')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан в')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменен в')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('is_contractor', models.BooleanField(default=False, verbose_name='Является подрядчиком?')),
            ],
            options={
                'verbose_name': 'Справочник организаций',
                'verbose_name_plural': 'Справочник организаций',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ИД')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан в')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменен в')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Справочник параметров',
                'verbose_name_plural': 'Справочник параметров',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ИД')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан в')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменен в')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Справочник должностей',
                'verbose_name_plural': 'Справочник должностей',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TechStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ИД')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан в')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменен в')),
                ('name', models.CharField(max_length=255, verbose_name='Состояние')),
            ],
            options={
                'verbose_name': 'Справочник состояний техники',
                'verbose_name_plural': 'Справочник состояний техники',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TechType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ИД')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан в')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменен в')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Справочник типов техники',
                'verbose_name_plural': 'Справочник типов техники',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentParameters',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ИД')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан в')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменен в')),
                ('value', models.IntegerField(blank=True, default=None, null=True, verbose_name='Значение')),
                ('parameters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_parameters', to='dict.parameters', verbose_name='Параметр ')),
            ],
            options={
                'verbose_name': 'Справочник параметров оборудования',
                'verbose_name_plural': 'Справочник параметров оборудования',
                'ordering': ['parameters'],
            },
        ),
    ]
