# Generated by Django 5.1.2 on 2025-03-20 09:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ИД')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан в')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменен в')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='название')),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
                'ordering': ['name'],
            },
        ),
    ]
