# Generated by Django 5.1.2 on 2025-01-17 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0001_initial'),
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActivityEvents',
            new_name='Event',
        ),
    ]
