# Generated by Django 5.1.2 on 2025-03-21 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0003_slings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slings',
            name='description',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Описание'),
        ),
    ]
