# Generated by Django 5.1.2 on 2025-01-20 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0002_rename_activityevents_event'),
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tech',
            name='org',
            field=models.ForeignKey(default='58920c3d-1047-4776-9589-30eeccb4914b', on_delete=django.db.models.deletion.CASCADE, related_name='techs', to='dict.org', verbose_name='Организация'),
            preserve_default=False,
        ),
    ]
