# Generated by Django 5.1.2 on 2025-01-21 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_tech_org'),
    ]

    operations = [
        migrations.CreateModel(
            name='VwShiftSummary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(verbose_name='Начало смены')),
                ('finish_time', models.DateTimeField(verbose_name='Окончание смены')),
                ('tech_gos_number', models.CharField(max_length=9, verbose_name='Гос. номер техники')),
                ('tech_type', models.CharField(max_length=255, verbose_name='Тип техники')),
                ('tech_status', models.CharField(max_length=255, verbose_name='Состояние техники')),
                ('org', models.CharField(max_length=255, verbose_name='Организация')),
                ('event_name', models.CharField(max_length=255, verbose_name='Название события')),
                ('event_start_time', models.DateTimeField(verbose_name='Время начала события')),
                ('event_finish_time', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания события')),
                ('event_duration_seconds', models.FloatField(verbose_name='Продолжительность события (в секундах)')),
                ('equipment_details', models.TextField(verbose_name='Детали оборудования')),
            ],
            options={
                'verbose_name': 'Сводка смен',
                'verbose_name_plural': 'Сводки смен',
                'db_table': 'vw_shift_summary',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='shiftevent',
            name='end_time',
        ),
    ]
