# Generated by Django 5.1.2 on 2025-01-21 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_vwshiftsummary_remove_shiftevent_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftevent',
            name='end_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Окончание состояния'),
        ),
    ]
