# Generated by Django 5.1.2 on 2025-01-28 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_shiftevent_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shifts',
            name='operator',
        ),
    ]
