# Generated by Django 5.1.2 on 2025-01-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0005_remove_shifts_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftevent',
            name='confirmation',
            field=models.BooleanField(default=False, verbose_name='Подтверждение'),
        ),
    ]
